// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalcETe72Gssf8hCQCmeOjI-T-RW2QYX8',
    appId: '1:527712323379:web:f742fdd10479cbb5836046',
    messagingSenderId: '527712323379',
    projectId: 'attendance-management-sy-8e7ff',
    authDomain: 'attendance-management-sy-8e7ff.firebaseapp.com',
    storageBucket: 'attendance-management-sy-8e7ff.appspot.com',
    measurementId: 'G-W9XQ68MZR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRJaDXysL06R3YxcvVvLblCUWgPOahvc',
    appId: '1:527712323379:android:346f1441cada1b07836046',
    messagingSenderId: '527712323379',
    projectId: 'attendance-management-sy-8e7ff',
    storageBucket: 'attendance-management-sy-8e7ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZtfS_CSqe1QO-ZdOrBMIt3nzZTREyes',
    appId: '1:527712323379:ios:9a892d5424d04a66836046',
    messagingSenderId: '527712323379',
    projectId: 'attendance-management-sy-8e7ff',
    storageBucket: 'attendance-management-sy-8e7ff.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZtfS_CSqe1QO-ZdOrBMIt3nzZTREyes',
    appId: '1:527712323379:ios:8ac7461bf2b3838f836046',
    messagingSenderId: '527712323379',
    projectId: 'attendance-management-sy-8e7ff',
    storageBucket: 'attendance-management-sy-8e7ff.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
